# Generated by Django 3.2.6 on 2021-08-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='М', max_length=1, verbose_name='Пол (м/ж)')),
                ('birthday', models.DateTimeField(verbose_name='Дата рождения')),
                ('tribe', models.CharField(blank=True, default='Арғын', max_length=256, null=True, verbose_name='Племя')),
                ('clan', models.CharField(blank=True, default='Қанжығалы', max_length=256, null=True, verbose_name='Род')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Телефоны')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='EMail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='person_father', to='tree.person')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mother_father', to='tree.person')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['surname'], name='person_surname_b68bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='person_name_b6df79_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['patronymic'], name='person_patrony_406166_idx'),
        ),
    ]
